package com.fyp.sctsma.model.userData

data class User(
    val rowId: String,
    val lockNumber: String,
    val username: String,
    val email: String,
    val password: String,
    val accountType: String,
    val contactName: String?,
    val contactEmail: String?,
    val contactPhoneNumber: String,
    val firstName: String,
    val lastName: String,
    val dateOfBirth: String?,
    val gender: String?,
    val nationality: String?,
    val addressLine1: String?,
    val city: String?,
    val state: String?,
    val postalCode: String?,
    val country: String?,
    val latitude: String?,
    val longitude: String?,
    val photoUrl: String?,
    val status: Int,
    val agreements: List<Any>,
    val roles: List<Role>,
    val accountLocked: Boolean,
    val enabled: Boolean,
    val authorities: List<Authority>,
    val accountNonLocked: Boolean,
    val accountNonExpired: Boolean,
    val credentialsNonExpired: Boolean
)